
package interfaces;

import javax.swing.JOptionPane;
import tareapokemones.Account;
import tareapokemones.Game;
import tareapokemones.Global;
import tareapokemones.NodeList;

/**
 *Ventana donde el usuario puede iniciar el juego.
 * Esta ventana permite al usuario poder visualizar los pokemones que posee y escoger el pokemon que desea participar en ese juego. También muestra los watts que tiene 
 * disponible y puede decidir cuantos watts desea apostar en el juego.
 * 
 * @author chris
 */
public class Play extends javax.swing.JFrame {
    Account user = Global.getUser();
    Game g = Global.getGame();
    
    /**
     * Constructor de la clase Play.
     * Inicializa los componentes de la interfaz gráfica, centra la ventana, desactiva la capacidad de redimensionamiento, muestra los watts disponibles
     * y además imprime los pokemones.
     */
    public Play() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        AvailableWatts.setText(Integer.toString(user.getWatts()));
        txtPOKEMONES.setText(user.getUtility().printPokemon());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtWatts = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AvailableWatts = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPOKEMONES = new javax.swing.JTextArea();
        btnStartGame = new javax.swing.JButton();
        txtChoose = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Play");
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtWatts, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, 30));

        jLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jLabel1.setText("Cuantos watts desea apostar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jLabel2.setText("Watts disponibles : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        AvailableWatts.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        AvailableWatts.setText("wats");
        jPanel1.add(AvailableWatts, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        txtPOKEMONES.setColumns(20);
        txtPOKEMONES.setRows(5);
        jScrollPane1.setViewportView(txtPOKEMONES);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 240, 120));

        btnStartGame.setBackground(new java.awt.Color(255, 255, 153));
        btnStartGame.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        btnStartGame.setText("Comenzar");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });
        jPanel1.add(btnStartGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 120, 30));
        jPanel1.add(txtChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 150, 30));

        jLabel5.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        jLabel5.setText("Elija el numero de pokemon para comenzar el juego ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 340, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        jLabel4.setText("Tus Pokemones");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        btnExit.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        btnExit.setText("Regresar");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 312, 120, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 280, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción realizada al presionar el botón para poder iniciar un nuevo juego.
     * Realiza una serie de validaciones de que el usuario ingrese los datos correctos permitidos para poder iniciar el juego.
     * 
     * @param evt El evento de acción que desencadena esta acción.
     */
    
    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        int poke;
        int w;

        try {
            if (txtChoose.getText().equals("") && txtWatts.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Complete el campo en blanco");
            }else{
                if(Integer.parseInt(txtWatts.getText()) > user.getWatts()){
                    JOptionPane.showMessageDialog(null, "No tienes ese saldo!");
                }else{

                    poke = Integer.parseInt(txtChoose.getText());
                    w = Integer.parseInt(txtWatts.getText());
                    int cont = 0;

                    NodeList currentNode = user.getUtility().getHead();
                    while(currentNode !=null){
                        if(cont == poke-1){
                            g.setCurrentWatts(w);
                            g.setInven(currentNode.getInventory());
                            g.setPk(currentNode.getPokemon());
                           
                        }
                        currentNode = currentNode.getNext();
                    }
                    cont =100;
                    int gifts = 0;
                    
                    while(cont<=900){
                        gifts += g.getInven().searchElement(cont).getCont();
                        cont+=100;
                    }
                    System.out.println(gifts);
                    
                    if(gifts < 2){
                        JOptionPane.showMessageDialog(null, "Regalos insuficientes, necesitas minimo 2");
                    }else{
                    
                        if (g.getPk().getName().equals("Pikachu")) {
                            PlayPikachu pikachu = new PlayPikachu();
                            pikachu.show();
                            this.dispose();
                        } else if (g.getPk().getName().equals("Pachirisu")) {
                            PlayPachirisu pachirisu = new PlayPachirisu();
                            pachirisu.show();
                            this.dispose();
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valor invalido!");
        }
    }//GEN-LAST:event_btnStartGameActionPerformed

    /**
     * Acción realizada al presionar el botón para regresar al menú principal.
     * Cierra la ventana actual y muestra la ventana del menú principal.
     * 
     * @param evt El evento de acción que desencadena esta acción.
     */
    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        vtnPrincipal principal = new vtnPrincipal();
        principal.show();
        this.dispose(); 
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * Método principal para ejecutar la aplicación.
     * Crea y muestra la ventana de jugar.
     * 
     * @param args Los argumentos de la línea de comandos (no utilizados en esta aplicación).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvailableWatts;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtChoose;
    private javax.swing.JTextArea txtPOKEMONES;
    private javax.swing.JTextField txtWatts;
    // End of variables declaration//GEN-END:variables
}
