package interfaces;

import java.util.Random;
import javax.swing.JOptionPane;
import tareapokemones.Account;
import tareapokemones.Global;
import tareapokemones.NodeList;

/**
 *
 * @author chris
 */
public class PlayPikachu extends javax.swing.JFrame {
        Account user = Global.getUser();
        NodeList game = Global.getPlay();
        Random random = new Random();
        int startNum = random.nextInt(1,13);
    /**
     * Creates new form PlayPikachu
     */
    public PlayPikachu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        txtCarta.setText(Integer.toString(startNum));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bntAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtCarta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PlayPikachu");
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setBackground(new java.awt.Color(255, 255, 153));
        btnExit.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        btnExit.setText("Regresar");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 130, 30));

        jLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        jLabel1.setText("Numero en juego del pikachu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        jLabel2.setText("La siguiente carta sera mas: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        bntAlta.setBackground(new java.awt.Color(255, 255, 153));
        bntAlta.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        bntAlta.setText("Alta");
        bntAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAltaActionPerformed(evt);
            }
        });
        jPanel1.add(bntAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 30));

        btnBaja.setBackground(new java.awt.Color(255, 255, 153));
        btnBaja.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        btnBaja.setText("Baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 100, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 153));
        jButton3.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        jButton3.setText("Como jugar");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 120, 30));

        txtCarta.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        txtCarta.setText("Carta");
        jPanel1.add(txtCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAltaActionPerformed

        int randomNum = random.nextInt(1,13);
        if (randomNum > startNum) {
            JOptionPane.showMessageDialog(null, "La carta del pikachu fue " + randomNum + "Ganaste!!");
            user.SumWatts(game.getCurrentWatts());
            Play p = new Play();
            p.show();
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "La carta del pikachu fue " + randomNum + "Perdiste!!");
            user.ResWatts(game.getCurrentWatts());
            Play p = new Play();
            p.show();
        }
        
        //txtCarta.setText(Integer.toString(randomNum));
        
    }//GEN-LAST:event_bntAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        int randomNum = random.nextInt(1,13);
        if (randomNum < startNum) {
            JOptionPane.showMessageDialog(null, "La carta del pikachu fue " + randomNum + "Ganaste!!");
            user.SumWatts(game.getCurrentWatts());
            Play p = new Play();
            p.show();
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "La carta del pikachu fue " + randomNum + "Perdiste!!");
            user.ResWatts(game.getCurrentWatts());
            Play p = new Play();
            p.show();
        }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayPikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayPikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayPikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayPikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayPikachu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtCarta;
    // End of variables declaration//GEN-END:variables
}
