
package interfaces;

import java.util.Random;
import javax.swing.JOptionPane;
import tareapokemones.Account;
import tareapokemones.Game;
import tareapokemones.Global;
import tareapokemones.List;

/**
 *Ventana para jugar "Adivina en lo que estoy pensando".
 * Esta ventana permite al usuario poder realizar su juego sugerido con el pokemon de Pachirisu.
 * 
 * @author chris
 */
public class PlayPachirisu extends javax.swing.JFrame {
    Account user = Global.getUser();
    Game game = Global.getGame();
    Random random = new Random();
    List Store = Global.getStore();
    
    
    /**
     * Constructor de la clase PlayPachirisu.
     * Inicializa los componentes de la interfaz gráfica, centra la ventana, desactiva la capacidad de redimensionamiento, y asigna texto recorrido en metodo inorder
     * hacia un textArea.
     */
    public PlayPachirisu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        TxtAreaStore.setText(Store.printgamePachi());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Txt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaStore = new javax.swing.JTextArea();
        txtChosse = new javax.swing.JTextField();
        btnChoose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PlayPachirisu");
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txt.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        Txt.setText("\"Adivina en que estoy pensando\"");
        jPanel1.add(Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        TxtAreaStore.setColumns(20);
        TxtAreaStore.setRows(5);
        jScrollPane1.setViewportView(TxtAreaStore);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, 240));

        txtChosse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChosseActionPerformed(evt);
            }
        });
        jPanel1.add(txtChosse, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 170, 30));

        btnChoose.setBackground(new java.awt.Color(255, 255, 153));
        btnChoose.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });
        jPanel1.add(btnChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 260, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Acción realizada cuando el usuario ingresa en el campo para escoger.
     * @param evt El evento de acción que desencadena esta acción.
     */
    private void txtChosseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChosseActionPerformed
        
    }//GEN-LAST:event_txtChosseActionPerformed

    /**
     * Acción realizada al presionar el botón para escoger.
     * @param evt El evento de acción que desencadena esta acción.
     */
    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        int num;
        String gift;
        
        try {
            num=Integer.parseInt(txtChosse.getText());
            int sumGifts =0;
            int cont =100;
            gift = Store.searchNum(num).getGift().getElement();
            
            while (cont <= 900) {
                if (game.getInven().searchElement(cont).getCont() != 0) {
                    sumGifts += game.getInven().searchElement(cont).getCont();
                }
                cont += 100;
            }
            
            cont = 100;
            
            int randomNum = random.nextInt(1,sumGifts);
           
            while (cont < 1000) {
                
                if (game.getInven().searchElement(cont).getCont() == randomNum){
                    if (game.getInven().searchElement(cont).getStore().getElement().equals(gift)) {
                        JOptionPane.showMessageDialog(null, "Ganaste, El pokemon estaba pensando en : " + gift +"Se te cargaran los watts");
                        user.SumWatts(game.getCurrentWatts());
                        break;
                    }else{
                        JOptionPane.showMessageDialog(null, "Perdiste, El pokemon estaba pensando en : "+ game.getInven().searchElement(cont).getStore().getElement() +"Se te cargaran los watts");
                        user.ResWatts(game.getCurrentWatts());
                        break;
                    }
                }else if(cont == 900){
                    int num1 = random.nextInt(1,9);
                    JOptionPane.showMessageDialog(null, "Perdiste, El pokemon estaba pensando en :"+ Store.searchNum(num1).getGift().getElement() +"Se te cargaran los watts");
                    user.ResWatts(game.getCurrentWatts());
                    
                }
                cont += 100;
            }
            Play p = new Play();
            p.show();
            this.dispose();
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valor invalido!!");
        }
    }//GEN-LAST:event_btnChooseActionPerformed

    /**
     * Método principal para ejecutar la aplicación.
     * Crea y muestra la ventana de playPachirisu.
     * 
     * @param args Los argumentos de la línea de comandos (no utilizados en esta aplicación).
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayPachirisu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayPachirisu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayPachirisu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayPachirisu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayPachirisu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Txt;
    private javax.swing.JTextArea TxtAreaStore;
    private javax.swing.JButton btnChoose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtChosse;
    // End of variables declaration//GEN-END:variables
}
