package interfaces;

import java.util.Random;
import javax.swing.JOptionPane;
import tareapokemones.Account;
import tareapokemones.Game;
import tareapokemones.Global;
import tareapokemones.NodeList;

/**
 *Ventana en donde se puede realizar el juego una vez seleccionado el pokemon Pikachu.
 * Esta ventana permite poder jugar con el pokemon Pikachu, seleccionando si la carta será más alta o más baja dependiendo de la carta a mostrar.
 * El usuario también puede ver la sección de cómo jugar.
 * 
 * @author chris
 */
public class PlayPikachu extends javax.swing.JFrame {
        Account user = Global.getUser();
        Game game = Global.getGame();
        Random random = new Random();
        int startNum = random.nextInt(1,13);
      
     /**
     * Constructor de la clase PlayPikachu.
     * Inicializa los componentes de la interfaz gráfica, centra la ventana, desactiva la capacidad de redimensionamiento.
     */
    public PlayPikachu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txtCarta.setText(Integer.toString(startNum));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bntAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtCarta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PlayPikachu");
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        jLabel1.setText("Numero en juego del pikachu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        jLabel2.setText("La siguiente carta sera mas: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        bntAlta.setBackground(new java.awt.Color(255, 255, 153));
        bntAlta.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        bntAlta.setText("Alta");
        bntAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAltaActionPerformed(evt);
            }
        });
        jPanel1.add(bntAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 30));

        btnBaja.setBackground(new java.awt.Color(255, 255, 153));
        btnBaja.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        btnBaja.setText("Baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 100, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 153));
        jButton3.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        jButton3.setText("Como jugar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 120, 30));

        txtCarta.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 12)); // NOI18N
        txtCarta.setText("Carta");
        jPanel1.add(txtCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción realizada al presionar el botón para que el usuario seleccione que la carta será mas alta de la mostrada.
     * @param evt El evento de acción que desencadena esta acción.
     */
    
    private void bntAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAltaActionPerformed

        int randomNum = random.nextInt(1,13);
        if (randomNum > startNum) {
            JOptionPane.showMessageDialog(null, "La carta del pikachu fue " + randomNum + " Ganaste!!");
            user.SumWatts(game.getCurrentWatts());
            Play p = new Play();
            p.show();
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "La carta del pikachu fue " + randomNum + " Perdiste!!");
            user.getUtility().search("Pikachu").getPokemon().SumRelation(game.getCurrentWatts());
            user.ResWatts(game.getCurrentWatts());
            Play p = new Play();
            p.show();
        }
        
        
    }//GEN-LAST:event_bntAltaActionPerformed

    /**
     * Acción realizada al presionar el botón para que el usuario seleccione que la carta será mas baja de la mostrada.
     * @param evt El evento de acción que desencadena esta acción.
     */
    
    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        int randomNum = random.nextInt(1,13);
        if (randomNum < startNum) {
            JOptionPane.showMessageDialog(null, "La carta del pikachu fue " + randomNum + " Ganaste!!");
            user.SumWatts(game.getCurrentWatts());
            Play p = new Play();
            p.show();
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "La carta del pikachu fue " + randomNum + " Perdiste!!");
            user.getUtility().search("Pikachu").getPokemon().SumRelation(game.getCurrentWatts());
            user.ResWatts(game.getCurrentWatts());
            Play p = new Play();
            p.show();
        }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Método principal para ejecutar la aplicación.
     * Crea y muestra la ventana de jugar con el Pikachu.
     * 
     * @param args Los argumentos de la línea de comandos (no utilizados en esta aplicación).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayPikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayPikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayPikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayPikachu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayPikachu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtCarta;
    // End of variables declaration//GEN-END:variables
}
