
package interfaces;

import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import tareapokemones.Account;
import tareapokemones.Global;
import tareapokemones.List;
import tareapokemones.Time;
import tareapokemones.Tree;

/**
 *
 * @author chris
 */
public class ShowPokemons extends javax.swing.JFrame {
    Account user = Global.getUser();
    List pokemons = Global.getPokemons();
    Time playtime = Global.getPlaytime();
    Tree invent = Global.getInvent();
    /**
     * Creates new form Showpokemon
     */
    public ShowPokemons() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txtAreaPokemones.setText(pokemons.printPokemon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaPokemones = new javax.swing.JTextArea();
        btnChoose = new javax.swing.JButton();
        txtnumPkemon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaPokemones.setColumns(20);
        txtAreaPokemones.setRows(5);
        jScrollPane1.setViewportView(txtAreaPokemones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, 150));

        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });
        jPanel1.add(btnChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel1.add(txtnumPkemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setText("Seleccione un pokemon: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        btnSalir.setText("x");
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        int num;
        long j;
        
        try {
            if(txtnumPkemon.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Porfavor introduzca un numero");
            }else{
                num = Integer.parseInt(txtnumPkemon.getText());
            
                if(num == 1){
                    
                    user.getUtility().insertarFinal(pokemons.getHead().getPokemon(),invent);
                    
                    long x = System.currentTimeMillis();
                    j = TimeUnit.MILLISECONDS.toSeconds(x);
                    playtime.setCurrentTime(j);

                }else if(num == 2){
                    user.getUtility().insertarFinal(pokemons.getHead().getPokemon(),invent);
                    
                    long x = System.currentTimeMillis();
                    j = TimeUnit.MILLISECONDS.toSeconds(x);
                    playtime.setCurrentTime(j);

                }else{
                    JOptionPane.showMessageDialog(null, "Este pokemon no existe, Porfavor elija un Pokemon existente");
                }   
            }
  
            vtnPrincipal ventenap = new vtnPrincipal();
            ventenap.show();
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valor invalido!");
        }
    }//GEN-LAST:event_btnChooseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowPokemons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowPokemons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowPokemons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowPokemons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowPokemons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaPokemones;
    private javax.swing.JTextField txtnumPkemon;
    // End of variables declaration//GEN-END:variables
}
