/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import tareapokemones.Account;
import tareapokemones.Global;
import tareapokemones.List;
import tareapokemones.NodeList;
import tareapokemones.Read;
import tareapokemones.Time;

/**
 *
 * @author chris
 */
public class vtnPrincipal extends javax.swing.JFrame {
    Account user = Global.getUser();
    List store = Global.getStore();
    Time playtime = Global.getPlaytime();
    long j = playtime.getCurrentTime();
    /**
     * Creates new form vtnPokemon
     */
    public vtnPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        long y = System.currentTimeMillis();
        long z = TimeUnit.MILLISECONDS.toSeconds(y);

        int seconds = (int)(z - j);
        playtime.setTime(seconds);
        Time.setText(Integer.toString(playtime.getTime()));

        txtWatts.setText(Integer.toString(user.getWatts()));
        Pokemones.setText(user.getUtility().printPokemon());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTienda = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        txtWatts = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnPokemon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Pokemones = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTienda.setBackground(new java.awt.Color(255, 255, 153));
        btnTienda.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        btnTienda.setText("Store");
        btnTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiendaActionPerformed(evt);
            }
        });
        jPanel1.add(btnTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 120, 30));

        btnGuardar.setBackground(new java.awt.Color(255, 255, 153));
        btnGuardar.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar Juego");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 120, 30));

        jLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        jLabel1.setText("Watts:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        jLabel2.setText("Time:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Time.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        Time.setText("Time");
        jPanel1.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        txtWatts.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        txtWatts.setText("Watts");
        jPanel1.add(txtWatts, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 280, 180));

        btnPokemon.setBackground(new java.awt.Color(255, 255, 153));
        btnPokemon.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        btnPokemon.setText("Pokemon");
        btnPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokemonActionPerformed(evt);
            }
        });
        jPanel1.add(btnPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 120, 30));

        Pokemones.setColumns(20);
        Pokemones.setRows(5);
        jScrollPane1.setViewportView(Pokemones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        jLabel3.setText("Pokemones");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 330, 470));

        btnJugar.setBackground(new java.awt.Color(255, 255, 153));
        btnJugar.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
        btnJugar.setText("Play");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        jPanel1.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokemonActionPerformed
        try {
            long y = System.currentTimeMillis();
            long z = TimeUnit.MILLISECONDS.toSeconds(y);
            int seconds = (int)(z - j);

            String result="";
            
            Time.setText(Integer.toString(seconds));
            playtime.setTime(seconds);
            user.SumWatts(10);
            
            
            int cont = 100;
            //txtWatts.setText(Integer.toString(user.getWatts()));
            NodeList currentNode = user.getUtility().getHead();
            while(currentNode!=null){
                result+= "Nombre: " + currentNode.getPokemon().getName() + "\n";
                result+= "Relacion: " + currentNode.getPokemon().getRelation() + "\n";
                result+= "Estado animo: " + currentNode.getPokemon().getStatus() + "\n";
                result+= "Inventario: \n";
                result+= currentNode.getInventory().inorder();
                
                currentNode = currentNode.getNext();
                cont+=100;
            }
            txtArea.setText(result);
            txtWatts.setText(Integer.toString(user.getWatts()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"NOOO");
        }
    }//GEN-LAST:event_btnPokemonActionPerformed

    private void btnTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiendaActionPerformed
        try {
            Store vtnStore = new Store();
            vtnStore.show();
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NOOOOOO");
        }
    }//GEN-LAST:event_btnTiendaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Read doc = new Read();
        try {
            doc.Save();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        Play game = new Play();
        game.show();
        this.dispose();
    }//GEN-LAST:event_btnJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Pokemones;
    private javax.swing.JLabel Time;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnPokemon;
    private javax.swing.JButton btnTienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JLabel txtWatts;
    // End of variables declaration//GEN-END:variables
}
